import { Product } from "./types/Product";

export const sampleProducts: Product[] = [
    {
        name: 'Bread Rolls',
        slug: 'bread-rolls',
        category: 'Appetizers',
        imageUrl: '../imgs/BreadRolls.PNG',
        price: 100.00,
        countInStock: 100,
        brand: '',
        rating: 4.5,
        numReviews: 10,
        description: 'highly recommeded',
    },
    {
        name: 'Buko Juice',
        slug: 'buko-juice',
        category: 'Drinks',
        imageUrl: '../imgs/Buko Juice.PNG',
        price: 150.00,
        countInStock: 100,
        brand: '',
        rating: 4.5,
        numReviews: 10,
        description: 'highly recommeded',
    },
    {
        name: 'Coke',
        slug: 'coke',
        category: 'Drinks',
        imageUrl: '../imgs/Coke.PNG',
        price: 50.00,
        countInStock: 0,
        brand: 'Coca-Cola',
        rating: 4.5,
        numReviews: 10,
        description: 'highly recommeded',
    },
    {
        name: 'Crackers',
        slug: 'crackers',
        category: 'Appetizers',
        imageUrl: '../imgs/Cracker.PNG',
        price: 80.00,
        countInStock: 100,
        brand: '',
        rating: 4.5,
        numReviews: 10,
        description: 'highly recommeded',
    },
    {
        name: 'Donut',
        slug: 'donut',
        category: 'Appetizers',
        imageUrl: '../imgs/Donut.PNG',
        price: 300.00,
        countInStock: 50,
        brand: 'Donkin Donut',
        rating: 4.5,
        numReviews: 10,
        description: 'highly recommeded',
    },
    {
        name: 'Halo-Halo',
        slug: 'halo-halo',
        category: 'Desserts',
        imageUrl: '../imgs/Halo Halo.PNG',
        price: 200.00,
        countInStock: 50,
        brand: '',
        rating: 4.5,
        numReviews: 10,
        description: 'highly recommeded',
    },
    {
        name: 'Ice Tea',
        slug: 'ice-tea',
        category: 'Drinks',
        imageUrl: '../imgs/Ice Tea.PNG',
        price: 25.00,
        countInStock: 100,
        brand: 'Tang',
        rating: 4.5,
        numReviews: 10,
        description: 'highly recommeded',
    },
    {
        name: 'Leche Flan',
        slug: 'leche-flan',
        category: 'Desserts',
        imageUrl: '../imgs/Leche Flan.PNG',
        price: 175.00,
        countInStock: 100,
        brand: '',
        rating: 4.5,
        numReviews: 10,
        description: 'highly recommeded',
    },
    {
        name: 'Fruit Salad',
        slug: 'fruit-salad',
        category: 'Meal',
        imageUrl: '../imgs/Salad.PNG',
        price: 130.00,
        countInStock: 50,
        brand: '',
        rating: 4.5,
        numReviews: 10,
        description: 'highly recommeded',
    },
]